### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pointer_event'

### ISSUE THREAD

**Issue by vmvz** [UIA-CAIR/pyVNC#2]
```
Traceback (most recent call last):
  File "/vnc.py", line 12, in <module>
    vnc.send_mouse()  # Left Clicks at x=200, y=200
  File "/Users/d/env/sgs/lib/python3.6/site-packages/pyVNC-0.1-py3.6.egg/pyVNC/Client.py", line 68, in send_mouse
AttributeError: 'NoneType' object has no attribute 'pointer_event'
Exception ignored in: <module 'threading' from '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by s3menzer** [comment]
Same for me
