### ISSUE TITLE
unsupported operand type(s) for &: 'str' and 'int'

### ISSUE THREAD

**Issue by alex2304** [UIA-CAIR/pyVNC#4]
Hi!
I've tried to run example from the README file, but it fails with the following:

```Traceback (most recent call last):
  File "../lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "../lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "../lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "../lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "../lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "../lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "../lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "../recognition/pyVNC/rfb.py", line 494, in dataReceived
    self._handler()
  File "../recognition/pyVNC/rfb.py", line 504, in _handle_expected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "../recognition/pyVNC/rfb.py", line 163, in _handle_vnc_auth
    self.vnc_request_password()
  File "../recognition/pyVNC/RFBToGUI.py", line 45, in vnc_request_password
    self.send_password(self.factory.password)
  File "../recognition/pyVNC/rfb.py", line 169, in send_password
    des = RFBDes(pw)
  File "../recognition/pyVNC/pyDes.py", line 410, in __init__
    self.setKey(key)
  File "../recognition/pyVNC/rfb.py", line 649, in setKey
    super(RFBDes, self).setKey(newkey)
  File "../recognition/pyVNC/pyDes.py", line 415, in setKey
    self.__create_sub_keys()
  File "../recognition/pyVNC/pyDes.py", line 463, in __create_sub_keys
    key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))
  File "../recognition/pyVNC/pyDes.py", line 429, in __String_to_BitList
    if ch & (1 << i) != 0:
builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'```

Are you going to support the library furthermore?

**Comment by nubonics** [comment]
> Hi!
> I've tried to run example from the README file, but it fails with the following:
> 
> ```
>   File "../lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
>     return callWithContext({"system": lp}, func, *args, **kw)
>   File "../lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
>     return context.call({ILogContext: newCtx}, func, *args, **kw)
>   File "../lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "../lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
>     return func(*args,**kw)
> --- <exception caught here> ---
>   File "../lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
>     why = getattr(selectable, method)()
>   File "../lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
>     return self._dataReceived(data)
>   File "../lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "../recognition/pyVNC/rfb.py", line 494, in dataReceived
>     self._handler()
>   File "../recognition/pyVNC/rfb.py", line 504, in _handle_expected
>     self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
>   File "../recognition/pyVNC/rfb.py", line 163, in _handle_vnc_auth
>     self.vnc_request_password()
>   File "../recognition/pyVNC/RFBToGUI.py", line 45, in vnc_request_password
>     self.send_password(self.factory.password)
>   File "../recognition/pyVNC/rfb.py", line 169, in send_password
>     des = RFBDes(pw)
>   File "../recognition/pyVNC/pyDes.py", line 410, in __init__
>     self.setKey(key)
>   File "../recognition/pyVNC/rfb.py", line 649, in setKey
>     super(RFBDes, self).setKey(newkey)
>   File "../recognition/pyVNC/pyDes.py", line 415, in setKey
>     self.__create_sub_keys()
>   File "../recognition/pyVNC/pyDes.py", line 463, in __create_sub_keys
>     key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))
>   File "../recognition/pyVNC/pyDes.py", line 429, in __String_to_BitList
>     if ch & (1 << i) != 0:
> builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'```
> 
> Are you going to support the library furthermore?
> ```

I also saw this on vncdotool, so, it has to do with one of the dependencies being upgraded, as downgrading vncdotool from 1.0.0 to 0.13.0 works as expected (without this error). I am not sure which library needs to be downgraded though... but if you do this error will most likely go away.

**Comment by nubonics** [comment]
ye...still does it...idk whats causing it tho...

**Comment by perara** [comment]
I'll check this out. Sorry for the delay.

**Comment by perara** [comment]
Could you paste me a bit of code of your example @alex2304 ?
pref the function at: ` File "../recognition/pyVNC/rfb.py", line 494, i`

**Comment by DaneelOlivaw1** [comment]
Same question

**Comment by luoruofeng** [comment]
Same question

**Comment by victorlapshev** [comment]
Same

**Comment by scomari** [comment]
In my case, I solved it by adding following line at line 429 in _pyDes.py_:
`                ch = ch if isinstance(ch, int) else ord(ch)
`
`ch` sometimes is an `int` and sometimes is a `str`, with this instruction you correctly cast it for the logical operation in the next line.
